// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMSZgG0JLvIRCH5Vej_otdckWt13p09c',
    appId: '1:354356648613:web:fdd14918350ea032398b4c',
    messagingSenderId: '354356648613',
    projectId: 'my-notes-app-146f1',
    authDomain: 'my-notes-app-146f1.firebaseapp.com',
    storageBucket: 'my-notes-app-146f1.appspot.com',
    measurementId: 'G-5EF1X9RDC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjJYQ253dfDOCcGXQzNtVkb7awveLFEs',
    appId: '1:354356648613:android:da852f5d6e712e1e398b4c',
    messagingSenderId: '354356648613',
    projectId: 'my-notes-app-146f1',
    storageBucket: 'my-notes-app-146f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EvRfKJ7eHvG_nYVqDMHYcxu2aQu-2S0',
    appId: '1:354356648613:ios:3358e87ef6629a62398b4c',
    messagingSenderId: '354356648613',
    projectId: 'my-notes-app-146f1',
    storageBucket: 'my-notes-app-146f1.appspot.com',
    iosClientId: '354356648613-a4uqnqc23hso9o7p0hb2cvl7maifrqcr.apps.googleusercontent.com',
    iosBundleId: 'com.mystuff.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8EvRfKJ7eHvG_nYVqDMHYcxu2aQu-2S0',
    appId: '1:354356648613:ios:3358e87ef6629a62398b4c',
    messagingSenderId: '354356648613',
    projectId: 'my-notes-app-146f1',
    storageBucket: 'my-notes-app-146f1.appspot.com',
    iosClientId: '354356648613-a4uqnqc23hso9o7p0hb2cvl7maifrqcr.apps.googleusercontent.com',
    iosBundleId: 'com.mystuff.notesapp',
  );
}
